linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goimports:
    local-prefixes: github.com/schroedinger-Hat/Daje
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - exportloopref

service:
  golangci-lint-version: 1.33.x
