name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  
jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v6

  golangci-lint:
    needs: commit_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: false
          args: --timeout 2m --config .golangci.yaml

  go_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run unit test
        run: go test

  checkhealth:
    runs-on: ubuntu-latest
    needs: go_test
    steps:
      - uses: actions/checkout@v4

      - name: Run checkhealth 
        run: make checkhealth

      - id: pr_calculate
        run: echo "pr=pr#${{ github.ref_name }}" | sed "s/\/merge//" >> "$GITHUB_OUTPUT"

      - id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: daje-${{ steps.pr_calculate.outputs.pr }}-${{ steps.sha_short.outputs.sha_short }}
          path: bin/daje

